In [16]:
# Installing library
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in d:\anaconda\lib\site-packages (9.3.0)

In [19]:
# Connecting to MySQL Database
import mysql.connector
from mysql.connector import Error

try:
    # Setting up the connection
    connection = mysql.connector.connect(
        host = '127.0.0.1',
        user = 'root',
        password = '', # Enter your MySQL Password here
        database = 'ola'
    )

    if connection.is_connected():
        print('Connection to MySQL database is successful.')

except Error as e:
    print('Error while connecting to MySQL.')

finally:
    if connection.is_connected():
        connection.close()
        print('MySQL connection closed.')

Connection to MySQL database is successful.
MySQL connection closed.

In [3]:
!pip install pymysql sqlalchemy pandas

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: sqlalchemy in d:\anaconda\lib\site-packages (2.0.34)
Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (2.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in d:\anaconda\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [21]:
import pandas as pd
from sqlalchemy import create_engine

# Format: 'mysql+pymysql://<username>:<password>@<host>/<dbname>'
engine = create_engine("mysql+pymysql://root:Password@localhost/ola")

# Run query and load result into DataFrame
df = pd.read_sql("SELECT * FROM cleaned_ola_data", engine)

# Show result
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle_Images
0,2024-07-26,0 days 14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,170.876952,84.873372,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,444,Cash,0,4.0,4.0,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25,0 days 22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.000000,30.000000,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30,0 days 19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.000000,130.000000,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22,0 days 03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,170.876952,84.873372,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,384,Cash,0,4.0,4.0,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02,0 days 09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.000000,80.000000,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [36]:
# #1 Retrieve all successful bookings:
df = pd.read_sql("SELECT * FROM cleaned_ola_data WHERE Booking_Status = 'Success' ", engine)

# Show result
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle_Images
0,2024-07-25,0 days 22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
1,2024-07-30,0 days 19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-02,0 days 09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
3,2024-07-13,0 days 04:42:00,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,173,UPI,41,3.4,4.6,https://cdn-icons-png.flaticon.com/128/3202/32...
4,2024-07-23,0 days 09:51:00,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,140,Cash,49,3.2,4.5,https://cdn-icons-png.flaticon.com/128/9983/99...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63962,2024-07-31,0 days 09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
63963,2024-07-31,0 days 15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
63964,2024-07-31,0 days 13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
63965,2024-07-31,0 days 14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
63966,2024-07-31,0 days 13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [35]:
# 2. Find the average ride distance for each vehicle type:
df = pd.read_sql("SELECT Vehicle_Type, AVG(Ride_Distance) as avg_distance FROM cleaned_ola_data GROUP BY Vehicle_Type", engine)

# Show result
df

  Vehicle_Type  avg_distance
0  Prime Sedan       15.7649
1         Bike       15.5331
2    Prime SUV       15.2745
3        eBike       15.5806
4         Mini       15.5101
5   Prime Plus       15.4475
6         Auto        6.2381

In [37]:
# 3. Get the total number of cancelled rides by customers:
df = pd.read_sql("SELECT COUNT(*) FROM cleaned_ola_data WHERE Booking_Status = 'Canceled by Customer'", engine)

# Show result
df

   COUNT(*)
0     10499

In [38]:
# 4. List the top 5 customers who booked the highest number of rides:

df = pd.read_sql("SELECT Customer_ID, COUNT(Booking_ID) as total_rides FROM cleaned_ola_data GROUP BY Customer_ID ORDER BY total_rides DESC LIMIT 5 ;", engine)

# Show result
df

  Customer_ID  total_rides
0   CID954071            5
1   CID199017            4
2   CID189965            4
3   CID263459            4
4   CID266327            4

In [39]:
# 5. Get the number of rides cancelled by drivers due to personal and car-related issues:
df = pd.read_sql("SELECT COUNT(*) FROM cleaned_ola_data WHERE Canceled_Rides_by_Driver = 'Personal & Car related issue';", engine)

# Show result
df

   COUNT(*)
0     91132

In [40]:
# 6. Find the maximum and minimum driver ratings for Prime Sedan bookings: 

df = pd.read_sql("SELECT MAX(Driver_Ratings) as max_rating, MIN(Driver_Ratings) as min_rating FROM cleaned_ola_data WHERE Vehicle_Type = 'Prime Sedan';", engine)

# Show result
df

   max_rating  min_rating
0         5.0         3.0

In [41]:
# 7. Retrieve all rides where payment was made using UPI:

df = pd.read_sql("SELECT * FROM cleaned_ola_data WHERE Payment_Method = 'UPI';", engine)

# Show result
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle_Images
0,2024-07-30,0 days 19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
1,2024-07-13,0 days 04:42:00,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,173,UPI,41,3.4,4.6,https://cdn-icons-png.flaticon.com/128/3202/32...
2,2024-07-27,0 days 13:18:00,CNR4524472111,Success,CID540929,Auto,Cox Town,Yelahanka,126.0,35.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,330,UPI,8,3.0,4.8,https://cdn-icons-png.flaticon.com/128/16526/1...
3,2024-07-16,0 days 09:54:00,CNR8181602032,Success,CID167642,Bike,Indiranagar,MG Road,70.0,95.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,378,UPI,18,4.8,4.1,https://cdn-icons-png.flaticon.com/128/9983/99...
4,2024-07-02,0 days 10:25:00,CNR8090918544,Success,CID640151,Bike,Magadi Road,HSR Layout,126.0,95.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,343,UPI,23,3.7,3.6,https://cdn-icons-png.flaticon.com/128/9983/99...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25876,2024-07-31,0 days 19:34:00,CNR4870774895,Success,CID266336,Prime Sedan,Marathahalli,Cox Town,189.0,30.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,280,UPI,38,3.4,4.1,https://cdn-icons-png.flaticon.com/128/14183/1...
25877,2024-07-31,0 days 03:00:00,CNR9738039746,Success,CID922711,eBike,Chickpet,RT Nagar,42.0,135.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,310,UPI,7,3.8,3.3,https://cdn-icons-png.flaticon.com/128/6839/68...
25878,2024-07-31,0 days 15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
25879,2024-07-31,0 days 14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
25880,2024-07-31,0 days 13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [42]:
# 8. Find the average customer rating per vehicle type:

df = pd.read_sql("SELECT Vehicle_Type, AVG(Customer_Rating) as avg_customer_rating FROM cleaned_ola_data GROUP BY Vehicle_Type;", engine)

# Show result
df

  Vehicle_Type  avg_customer_rating
0  Prime Sedan             4.001002
1         Bike             3.995874
2    Prime SUV             3.999618
3        eBike             3.992474
4         Mini             3.998591
5   Prime Plus             4.005861
6         Auto             3.999261

In [43]:
# 9. Calculate the total booking value of rides completed successfully:

df = pd.read_sql("SELECT SUM(Booking_Value) AS total_successful_ride_value FROM cleaned_ola_data WHERE Booking_Status = 'Success';", engine)
# Show result
df

   total_successful_ride_value
0                   35080467.0

In [44]:
# 10. List all incomplete rides along with the reason
df = pd.read_sql("SELECT Booking_ID, Incomplete_Rides_Reason FROM cleaned_ola_data WHERE Incomplete_Rides = 'Yes';", engine)

# Show result
df

         Booking_ID Incomplete_Rides_Reason
0     CNR5176704322         Customer Demand
1     CNR9312632867       Vehicle Breakdown
2     CNR7924302885         Customer Demand
3     CNR1640228587             Other Issue
4     CNR7623690602             Other Issue
...             ...                     ...
3921  CNR5546265534         Customer Demand
3922  CNR1954831907       Vehicle Breakdown
3923  CNR1271821250       Vehicle Breakdown
3924  CNR4652634649       Vehicle Breakdown
3925  CNR5427755403             Other Issue

[3926 rows x 2 columns]